apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejemplo-python
spec:
  template:
    spec:
      containers:
        - name: ejemplo-python
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
