version: '3.4'

services:
  backend:
    image: equipo01-backend-python:latest
    build: .
    environment:
      - SECRET_KEY=cp&6^d7rb@gohfjt4ny8xz2w%!3m10uvlsik9aqe5
      - DATABASE_URL=mysql://root:password@database:3306/db
      - WAIT_HOSTS=database:3306
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: mariadb:10.4.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
