apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: ejemplo-apps
      app.kubernetes.io/managed-by: kustomize
      team: plataforma
